name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip build-essential python3-setuptools python3-wheel libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf automake cmake libtool pkg-config

      - name: Install Buildozer
        run: |
          pip install --user buildozer

      - name: Build APK
        run: |
          ~/.local/bin/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mediscan-apk
          path: bin/*.apk